README.md
bin/http-server
lib/http-server.js
package.json
test/http-server-test.js

This pull request implements the same feautre like https://github.com/nodeapps/http-server/pull/133 .  
However it uses the `http-proxy` module instead of the `proxy-middleware` module.
From https://github.com/nodeapps/http-server/pull/133 :
This pull request would add a new feature to *http-server*.  
It is called **proxy** as it uses the *proxy-middleware* module to redirect unresolvable requests to a given url. 
Checkout the pull request:
```
git clone https://github.com/jantimon/http-server.git --branch feature/node-http-proxy --single-branch --depth 1
cd http-server
npm install
```
Example usage
```
node bin/http-server -P http://blog.nodejitsu.com/
```
[Open http://localhost:8080/img/](http://localhost:8080/img/) and it will resolve `http-server/public/img` just like before.
Next …

Add --proxy setting (using http-proxy)

---

bin/http-server
lib/http-server.js
package.json
test/http-server-test.js

Without this patch, http-server returns 404 on the preflight request (method: 'OPTIONS'). You can see the problem by loading an XHR request in Chrome.

Get CORS support working with XHR preflight

---

bin/http-server

Added useful tip with local addresses not to run `ifconfig` command every time you want to recall your local IP.
Once again :wink: #60

Added useful tip with local addresses

---

bin/http-server

I run http-server in a docker container.
When docker stop a container, it send a SIGTERM, and after a timeout send a SIGKILL.
By default, node && iojs trap sigterm and does nothing. This trigger the timeout on docker to send a sigkill. 
So basically, stopping a container running `http-server` take some seconds.
Now, it's almost instantaneous. :boom:

Handle sigterm to exit

---

lib/http-server.js

This closes https://github.com/indexzero/http-server/issues/158
Should be ok to merge. I strongly feel this is the desired behavior - in normal circumstances you should be able to explicitly set `max-age` to zero.

Allows explicitly setting cache to 0, closes #158

---

README.md
bin/http-server

I've done a modification which enables using local time in log messages, and added an option `-U --utc` which enables UTC time format.

Add option which enables UTC time format for log messages

---

README.md

The installation portion to the readme instructs the user to use a shell script provided by npm to install the package manager. This is harmful because it leaves open way too many ambiguities. A safer way would be to instruct the user to use a package manager to install npm (even though most Node installers provide npm by default now).

Pointing to scripts online is harmful

---

bin/http-server

add forward-slash to url output when module starts
fix for iTerm2 users who use the `CMD+left-mouse click` to open url
links from the application's window

Resolves indexzero/http-server#219

---

bin/http-server

When you specify an address with -a, http-server reports that it listens to all the available interfaces but serves only the address specified (as it should)

Report correct server address

---

bin/http-server

The `union` module iterates over a map of headers. If the supplied `headers` object is a thing and `colors` is loaded in it's "normal" (not "safe") mode, `union` will try to set headers like "bold" and "red" which contain shell color codes. Node will complain about these invalid header character and throw an exception:
```
_http_outgoing.js:351
throw new TypeError('The header content contains invalid characters');
^
TypeError: The header content contains invalid characters
at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:351:13)
at ResponseStream.writeHead (/Users/lnwdr/temp/testproject/node_modules/http-server/node_modules/union/lib/response-stream.js:78:21)
```

Use safe colors to avoid header problems

---

bin/http-server

The `protocol` variable is set earlier in the code to `"https://"` or `"http://"`, depending on whether SSL is being used. Adding two more slashes results in `"https:////address"` and causes issues on some machines, so this removes the extra slashes :smile:

Remove extra slashes (fixes `-o` command)

---

package-lock.json

This adds `package-lock.json` which will help prevent future dependency problems. From the [npm documentation](https://docs.npmjs.com/files/package-locks):
> This file describes an exact, and more importantly reproducible `node_modules` tree. Once it's present, any future installation will base its work off this file, instead of recalculating dependency versions off `package.json`.

Add npm package-lock

---

README.md
bin/http-server

Continuing work by @paked in #187, this adds the useful feature of
logging the remote client IP address. I personally use this feature in
Apache often at work, and it would be nice to have it here as well!
The addition is the `--log-ip` option, which adds the client IP to the
log message between the date and the request method and url.
Fixes #184

add option for client IP logging

---

test/http-server-test.js

Hello, been looking around at making some further contributions, and came across an issue where vows would swallow errors, making it very difficult to debug.  Very simple one liner (with a comment to explain its purpose).
What was a fairly simple issue (I had a process listening on 8081 that I'd forgotten about), prevented my tests from passing, with no meaningfully related error output.  This cost me a little over an hour of troubleshooting, until I was able to find the magic `uncaughtException` event, which clearly spelled out the problem.  Hoping to contribute back to help the next person!
Validating the behavior difference is fairly simple, just start an http-server on 8081 before executing tests on master vs this branch.
Cheers!

Prevent vows from swallowing test errors on uncaught errors within topics

---

lib/http-server.js

This is a fix for https://github.com/indexzero/http-server/issues/149.
It accounts for the special case of `cache` being set to `-1` and, in that case, sets the cache header to `no-cache, no-store, must-revalidate` to really make sure nothing tries to cache responses from the server.

Aggressively turn off caching when cache time set to -1

---

package-lock.json
package.json

Removed common-style (deprecated, depends on unpatched packages)

Updated dependencies to fix security issues

---

README.md
bin/http-server
lib/http-server.js
package.json
test/http-server-test.js

Built on the work of @jondlm in #51. Using what I figured was the most popular basic auth library: https://www.npmjs.com/package/basic-auth
Can be configured with CLI options or env variables (separated out into its own commit in case you don't want that).
I've erred on the generous side when it comes to tests, as people will probably be pretty peeved if this stops working in some non-obvious way!

Add HTTP Basic Auth

---

lib/http-server.js

`http-proxy` does not handle errors by default and would just throw crashing the server. This PR adds error handling with rudimental logging.

Handle proxy errors

---

README.md

Documents the `-P http://localhost:8080?` proxy hack from https://github.com/indexzero/http-server/issues/338#issuecomment-338601211 in the Readme
Fixes #338, closes #331, closes #194, closes #80

document catch-all redirect hack

---

package.json

I think Node@6 is a reasonable minimum, even though it's not supported for much longer. Earlier releases may have issues that a simple http server doesn't need to accommodate. Instead, we should require that users of `http-server` only use the latest versions of Node.
Fixes #232

require at least node 6

---

bin/http-server

set process title to 'http-server' so it can be easily killed.
Fixes #333

add process title

---

package-lock.json
package.json

force to use `ecstatic` v3.3.2 in tests
Same as https://github.com/http-party/http-server/issues/525#issuecomment-551301695, the version of  `ecstatic` used in tests is different from it when installing `http-server` globally or as a dependency. 
#525 only appears when using `ecstatic` v3.3.2 .
It is very confusing in tests.
change the version of `ecstatic` in ``package-lock.json`` to 3.3.2

force to use ecstatic v3.3.2 in tests

---

.travis.yml

Adds `osx` as a test OS for Travis CI.
I'd like to test on BSD as well, but as far as I can tell Travis doesn't
and won't support it. Supporting OSX should sort of handle BSD testing,
though it's no substitute for the real thing.

Test on osx

---

bin/http-server
lib/http-server.js

Enhancement
Now `Accept-Ranges: bytes` header is sent with every response by default.
N/A
I think sending `Accept-Ranges: bytes` with every response is pretty benign, but surely the behaviour of some programs might be affected with this header (*i.e.* they might try to stream instead of downloading the whole file). If this is a concern, a new command-line flag can be added.
N/A

Send Accept-Ranges: bytes with every response

---

lib/http-server.js
test/fixtures/root/htmlButNot
test/http-server-test.js

Fixes #160 by ensuring that when `--ext` is `true` or `'html'`, and no overriding content-type is set, the content-type is set to `text/html`.

Fix `--ext` with HTML

---

lib/http-server.js

This is a new implementation of #387, but fixed.
Previously, we added a function which would use logFn if it exists.
Since this is all this function does, if logFn does not exist, we don't
need to add the function at all.
This should, in theory, provide a small performance boost as well, since
the operation of checking for logFn doesn't need to be performed on
every request log.

Only add logFn function to before if logFn exists

---

lib/http-server.js
test/http-server-test.js

Fix basic auth options type issue

---

bin/http-server
package-lock.json
package.json

Fixes [GHSA-vh95-rmgr-6w4m](https://github.com/advisories/GHSA-vh95-rmgr-6w4m) present in versions of `minimist` before 1.2.2.
- `optimist` [is deprecated](https://github.com/substack/node-optimist) and suggests using `minimist` directly or using `yargs`. It seemed relatively straightforward to use `minimist` directly here.
- I was able to resolve the remaining reference to an outdated version of `minimist` by upgrading a sub-dependency, `mkdirp`.
It doesn’t look like there are a ton (any?) tests associated with the command-line interface …

Fix security vulnerability GHSA-vh95-rmgr-6w4m.

---

doc/http-server.1
package.json

This page will be added to `man` when http-server is installed. The page is based on the CLI help dialog.

add man page

---

README.md

Used table format for README summary of Commands.

---

package.json

The `hs` alias is non-obvious and conflicts with at least one other tool. This is better suited as a user-defined alias, instead of the package setting two for itself.
Fixes #695

Remove hs alias

---

bin/http-server

Resolves #529 by adding server settings logs to startup.
Changed the startup function to output logs of common server settings.
No unit tests added, as this is not changing any service functionality.
Affects all server startup commands.
None
Validate that the settings are displayed appropriately.

Adding output of server settings on startup

---

bin/http-server

When using address `0.0.0.0`, open directly to `127.0.0.1`. Fixes an issue where Windows doesn't translate this address correctly.
fixes #727

open to 127.0.0.1 when host is 0.0.0.0

---

lib/core/show-dir/index.js
test/main.test.js
test/showdir-href-encoding.test.js
test/showdir-search-encoding.test.js
test/showdir-with-spaces.test.js

Hi there. Thanks for your all continuous work on this! I've fixed #661, please review.
---
https://github.com/http-party/http-server/issues/661
Paths in directory listing to be relative
Before: 
After:
I'm not sure that the tests are fixed properly, so please focus on those.
I tested in following way:
1. Run `npm run test`
There was no error and it says "371 passing".
2. Run `./bin/http-server ./`, check the paths on `http://localhost:8080`
Result image is above.

Use relative paths in directory listing #661

---

test/304.test.js
test/core-error.test.js
test/core.test.js
test/express-error.test.js
test/express.test.js
test/showdir-href-encoding.test.js
test/showdir-pathname-encoding.test.js
test/showdir-search-encoding.test.js
test/showdir-with-spaces.test.js

Replaces tests which used a random port with `portfinder` to grab an open port every time.
fixes #723

Fix tests EACCESS by finding an open port every time

---

bin/http-server
package-lock.json
package.json

Alternative to #783 -- instead of locking the last version of colors, use chalk: same size, same syntax, more widespread (hopefully more stable). Currently use version 4 so that it can be `require`d rather than `import`ed. Switch to ESM can be done in later PR.
- [n/a] Provide tests for the changes (unless documentation-only)
- [n/a] Documented any new features, CLI switches, etc. (if applicable)
- [n/a] Server `--help` output
- [n/a] README.md
- [n/a] doc/http-server.1 (use the same format as other entries)

Switch from colors to chalk

---

lib/core/status-handlers.js
package.json

Handle the case when headers are already sent because of an error -- we want to report the error, not hide it behind "headers already sent". Also bump Node requirement to match versions not affected by #756 .
#756

Make sure headers are not set twice on error

---

README.md

rework the url for the build status badge to new shields.io format

fix broken shields.io badge

---

bin/http-server

Ref : https://www.grouparoo.com/blog/node-js-and-ipv6

set default listener on ipv4 and ipv6 interfaces

---

README.md
bin/http-server
doc/http-server.1
test/cli.test.js

Difference/improvements over #885:
- Semantically identical to `curl -H` and `curl --header` [^1]
- Empty headers are allowed (RFC 7230)
- Includes tests
Sorry :)
Resolves #884
[^1]: https://curl.se/docs/manpage.html#-H

Added option for custom headers

---

.github/workflows/node.js.yml
package.json

It seems like upgrading `tap` to `21.x.x` has caused tests to fail on most Node versions in the CI. `tap 21` only supports `node>=20`, so tests fail when run on older versions, also test coverage and reporter settings hanged, so `tap` always returns exit code `1`.
Sorting out all this, I also ran into several other issues:
- Node versions 12 and 14, which are used in tests, are significantly outdated, causing `setup-node` to struggle with locating compatible images. At least, now it shows following error: `Unable to find Node version '12.x' for platform darwin and architecture arm64.`
- `checkout@v2` and `setup-node@v2` are outdated and still rely on Node 12.
To resolve all this I did following
- Downgraded to `tap@20`, which still supports Node 18
- It seems like `spec` reporter is not …

Fix Node.js CI workflow

---

README.md
bin/http-server
lib/http-server.js
test/main.test.js

Rebased and update stale PR https://github.com/http-party/http-server/pull/294.
Fixes https://github.com/http-party/http-server/issues/139.

Add `--base-dir` to cli options to specify base path

---

lib/http-server.js

Properly proxy WebSocket "upgrade" connections. Without this change any attempt to use `http-server` as a proxy for WebSocket does not work. The code also handles error cases when WebSocket server abruptly closes connection (or a network device dies between client and server). Other PRs fixing the same issue cause http-server to throw error and exit on WebSocket connection errors.
It's a useful addition to http-server for people developing WebSocket applications. There's no WebSocket proxy for Node.js easy to use from command line. This pull request makes http-server more versatile and helps local dev workflows.
The change is as minimal as possible, no code style changes, no whitespace changes etc. Please merge.
Fixes #142.
Note: cannot provide unit tests for this change.
Note: this …

Proxy WebSocket connections with error handling
