bin/http-server

Complete renaming of log() to logger.info()

---

.github/ISSUE_TEMPLATE
.github/PULL_REQUEST_TEMPLATE

Added templates for issues and pull requests in a `.github` folder.
Fixes #500.

Add issue and pull request templates

---

package-lock.json
package.json
test/http-server-test.js

make the tests run on Node 12
https://github.com/http-party/http-server/pull/569#issuecomment-551117979
* upgrade `vows` to 0.8.3
* add cleanup after all the tests finish

make the tests able to run on Node 12

---

bin/http-server
lib/http-server.js

-t flag to control timeout

---

README.md

Added the `--no-dotfiles` option  in `README.md` because it's available but not documented.

Add README `--no-dotfiles` option

---

.travis.yml

ensure #569 continue to work on Windows
test on Windows in Travis CI

test on Windows in Travis CI

---

README.md

Fix README badges to point to `http-party` repo rather than old `indexzero` repo.

Update readme badges to use new repo

---

README.md
bin/http-server

Implement the version flag

---

README.md

Add TLS/SSL usage description

---

bin/http-server

Add --version CLI parameter
Added the --version CLI argument and show the version on package.json if the argument is present.
run
`node bin/http-server --version`
it should print the version on package.json

Add CLI --version parameter

---

.gitignore

make .gitignore works
update `.gitignore` file
\-
\-
\-

correct gitignore

---

README.md

See https://github.com/http-party/http-server/issues/217
Updated the readme to document `process.env.PORT`.

Mention process.env.PORT in options

---

package.json

Make the project easier to find
Added a keyword in package.json
No code changes were made

Added a keyword in package.json

---

bin/http-server

Suggesting to remove overwriting 0.0.0.0
fixes #615
Simply removed relevant code.

remove 0.0.0.0 overwriting

---

test/range.test.js

Should fix the Windows specific CI failure that happens with GH and did not happen with Travis
fixes #703

Account for CRLF in a test

---

LICENSE

- [n/a] Tests for the changes have been added (for bug fixes / features)
Make GitHub license detection work again.

Remove line break from LICENSE

---

lib/core/index.js
test/check-headers.js
test/cli.test.js
test/content-type.test.js
test/custom-content-type-file-secret.test.js
test/custom-content-type-file.test.js
test/custom-content-type.test.js
test/headers.test.js
test/public/subdir/app.wasm

Fixes #480
Inlines https://github.com/broofa/mime/blob/v1.x/mime.js#L104 because `charset` was removed from `mime` v2, so this makes it easier to update `mime`.

Remove charset from header of binary files

---

bin/http-server

Adds version number to server startup output

---

package-lock.json
package.json

Version 14.11.0 wasn't working due to what appears to be a broken dependency. I think this might be related to tapjs/tapjs/issues/1037.
N/A
N/A

chore: update tap

---

LICENSE

chore: update readme license
